name: Anomaly Report
description: Report a bug or inconsistency in the ZYB ecosystem.
title: "[ANOMALY]: <Short Description>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **SYSTEM STATUS: ALERT**
        Please describe the anomaly with precision. Vague reports will be closed.

  - type: textarea
    id: description
    attributes:
      label: Description of Anomaly
      description: What happened? What did you expect to happen?
      placeholder: The Prover failed to generate a proof for circuit X...
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: "1. Run command... 2. Click button..."
      placeholder: "1. zyb-cli prove --input data.json"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      options:
        - zyb-kernel
        - zyb-circuits
        - zyb-services
        - zyb-apps
        - zyb-cli
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: System Logs / Stack Trace
      render: shell